#!/bin/sh

set -e

echo "Boostrapping capsimg..."
cd CAPSImg
rm -Rf autom4te.cache
echo "Running autoheader"
autoheader
echo "Running autoconf"
autoconf

echo "Bootstrap done, you can now run ./configure"
